import { requestJson, UPLOAD_TIMEOUT_MS } from "./request";
import type {
  SignResponse,
  UploadHistoryItem,
  UploadHistoryResponse,
  UploadProvider,
  UploadResult
} from "./types";

export function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

export function fileToResult(sign: SignResponse): UploadResult {
  const url = sign.publicUrl;
  return {
    uploadId: crypto.randomUUID(),
    uploadedAt: new Date().toISOString(),
    provider: sign.provider,
    providerLabel: sign.providerLabel,
    cdnBaseUrl: sign.cdnBaseUrl,
    objectKey: sign.objectKey,
    originalUrl: url,
    html: `<img src="${url}" alt="" />`,
    markdown: `![](${url})`,
    bbcode: `[img]${url}[/img]`
  };
}

export async function requestUploadSignature(
  file: File,
  token: string,
  prefix: string,
  provider: UploadProvider,
  signal?: AbortSignal
) {
  return requestJson<SignResponse>("/api/sign-upload", {
    signal,
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-upload-token": token
    },
    body: JSON.stringify({
      fileName: file.name,
      contentType: file.type,
      fileSize: file.size,
      pathPrefix: prefix,
      provider
    })
  });
}

export function uploadToSignedUrl(
  file: File,
  sign: SignResponse,
  onProgress: (progress: number) => void,
  signal?: AbortSignal,
  timeoutMs = UPLOAD_TIMEOUT_MS
) {
  return new Promise<void>((resolve, reject) => {
    if (signal?.aborted) { reject(signal.reason); return; }
    const xhr = new XMLHttpRequest();
    const abort = () => xhr.abort();
    const finish = (error?: unknown) => {
      signal?.removeEventListener("abort", abort);
      xhr.onload = xhr.onerror = xhr.ontimeout = xhr.onabort = null;
      xhr.upload.onprogress = null;
      if (error) reject(error); else resolve();
    };
    try {
      xhr.open(sign.upload.method, sign.upload.url, true);
      xhr.timeout = timeoutMs;
      Object.entries(sign.upload.headers ?? sign.headers).forEach(([key, value]) => {
        // Content-Length is generated by the browser from the request body.
        if (key.toLowerCase() !== "content-length") xhr.setRequestHeader(key, value);
      });
      let previousProgress = -1;
      xhr.upload.onprogress = event => {
        if (!event.lengthComputable) return;
        const progress = Math.round((event.loaded / event.total) * 100);
        if (progress !== previousProgress) {
          previousProgress = progress;
          onProgress(progress);
        }
      };
      xhr.onload = () => finish(xhr.status >= 200 && xhr.status < 300
        ? undefined : new Error(`上传失败，${sign.providerLabel} 返回 ${xhr.status}`));
      xhr.onerror = () => finish(new Error("上传过程中网络异常"));
      xhr.ontimeout = () => finish(new Error("上传超时，请重试"));
      xhr.onabort = () => finish(signal?.reason ?? new DOMException("上传已取消", "AbortError"));
      signal?.addEventListener("abort", abort, { once: true });
      if (sign.upload.method === "POST") {
        const formData = new FormData();
        Object.entries(sign.upload.fields ?? {}).forEach(([key, value]) => {
          if (key !== "file") formData.append(key, value);
        });
        formData.append("file", file);
        xhr.send(formData);
      } else {
        xhr.send(file);
      }
    } catch (error) { finish(error); }
  });
}

export async function saveUploadHistory(
  file: File,
  result: UploadResult,
  token: string,
  signal?: AbortSignal
) {
  return requestJson<{ item: UploadHistoryItem }>("/api/upload-history", {
    signal,
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-upload-token": token
    },
    body: JSON.stringify({
      uploadId: result.uploadId,
      uploadedAt: result.uploadedAt,
      provider: result.provider,
      objectKey: result.objectKey,
      originalUrl: result.originalUrl,
      fileName: file.name || "clipboard-image.png",
      contentType: file.type,
      fileSize: file.size
    })
  });
}

export async function fetchUploadHistory(token: string, cursor?: string | null, signal?: AbortSignal) {
  const search = new URLSearchParams({ limit: "24" });
  if (cursor) search.set("cursor", cursor);

  return requestJson<UploadHistoryResponse>(`/api/upload-history?${search.toString()}`, {
    signal,
    headers: { "x-upload-token": token }
  });
}
